/** The story from the old About section (word for word, apart from the "right now" line). Links use the global .link style;
 * data-preview shows an image card on hover (see StoryText). */
export const STORY_PARAGRAPHS: string[] = [
  "i'm just a guy that loves creating things.",
  'since i was 7, computers have been my constant passion. it all began with playing games on <a href="https://www.friv.com/" target="_blank" rel="noopener noreferrer" class="link">friv</a>, especially fire boy and water girl. i was instantly hooked.',
  'by the time i hit 12, things got serious. i discovered how to create basic websites, and that was it, i was addicted! from there, i started building websites, apps, <a href="https://imgur.com/CveUWRS" target="_blank" rel="noopener noreferrer" class="link" data-preview="/story/competitions.jpg" data-caption="class IV, international rank 4 (the kid in the red circle)">attending competitions</a>, exploring anything i could create with a computer.',
  'in 2025, i joined an overseas agency. it was a game-changing experience, where i generated over ₹3 lakh in revenue for the agency. <a href="/past" class="link">although i eventually moved on</a>, my passion for creating hasn\'t wavered one bit.',
  'in college, i started participating in hackathons, <a href="https://www.linkedin.com/posts/shrit1401_we-won-nmkrv-college-hackathon-we-built-activity-7433605535196725248-ctiX?utm_source=share&utm_medium=member_desktop&rcm=ACoAADuXot0BD4BdEJRqI6kA-AbQ8tNBvPNHC4I" target="_blank" rel="noopener noreferrer" class="link" data-preview="https://cdn.sanity.io/images/2k2xduz5/production/4df1cf8f847fa80112ec9ba046d9202c638fdf93-1280x993.png?w=700" data-caption="1st place, NMKRV hackathon">won a few of them</a>, then went on to complete an internship in my first year.',
  'and right now, i’m building <a href="https://www.heytappr.com" target="_blank" rel="noopener noreferrer" class="link" data-preview="/story/heytappr.mp4" data-poster="/story/heytappr.jpg" data-caption="heytappr, walking a user through a live site">heytappr</a>, helping product managers get their stuck users unstuck. still iterating on it, one version at a time.',
  "i stay connected through my weekly newsletter, where i share everything, from what i'm working on, to life lessons and the ups and downs of my journey. want to be a part of it? drop your email below, and i'll send it straight to your inbox!",
];
